/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[193] =
    {   0,
        0,    0,    0,    0,   75,   75,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   83,   78,   81,   80,   82,   77,
       77,   75,   75,   75,   75,   75,   75,   75,   75,   59,
       58,   58,   54,   56,   55,   59,   59,   53,   47,   46,
       46,   41,   43,   42,   47,   47,   40,   33,   31,   34,
       32,   29,   28,   26,   25,   20,   19,   23,   22,   22,
        4,    2,    4,    3,   17,   16,   16,   11,   13,   12,
       17,   17,   10,   79,    0,    0,   77,   77,   77,   75,
       75,   75,   75,   75,   75,   75,   61,   67,   75,   75,

       74,   65,   75,   63,   62,   58,   58,   58,   50,   52,
       51,   48,    0,   45,   46,   46,   37,   39,   38,   35,
        0,    0,    0,    0,   32,   32,    0,    0,    0,    0,
       19,    0,   22,   22,   22,    2,    0,    0,    3,    3,
       15,   16,   16,    7,    9,    8,    5,    0,   76,   73,
       72,   71,   70,   69,   68,   60,   66,   64,   57,   58,
        0,   46,   46,   44,   45,    0,   30,    0,   27,    0,
       24,    0,   18,    0,   21,   22,    1,    0,   16,   16,
       14,   15,    0,    0,   46,    0,   16,    0,   49,   36,
        6,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    4,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    1,    7,    8,    9,
       10,   11,   12,   13,    7,    7,    7,    1,   14,    1,
        1,    1,    1,   15,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   16,    1,    1,    1,    1,    7,    7,    7,   17,

        7,    7,    1,   18,   19,    1,    1,   20,    1,   21,
        1,   22,    1,    1,    1,   23,    1,   24,    1,   25,
        1,    1,   26,   27,   28,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[29] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[221] =
    {   0,
        0,    2,    4,    6,    8,   32,   56,   83,  110,  137,
        9,   11,  326,  325,  324,  323,  322,  321,   13,   15,
       33,   35,  164,  191,  322,  329,  315,   17,  329,   19,
       37,    0,  212,  318,   27,  317,   44,  316,  315,  329,
       39,   61,  290,  289,  288,    0,    0,  329,  329,   63,
       65,  287,  286,  285,    0,    0,  329,  329,   67,   75,
      307,  329,   71,  329,   73,  329,   77,  329,   79,   88,
      329,   90,   91,  306,  329,   93,   98,  282,  281,  280,
        0,    0,  329,  329,  299,  100,  114,  104,  106,    0,
      302,  301,  300,  299,  298,  297,  329,  329,  296,  295,

      329,  329,  294,  329,  329,  116,  121,  125,  329,  329,
      329,  329,    0,  127,  129,  132,  329,  329,  329,  329,
        0,  141,  143,  145,  292,  291,  148,  153,  155,  160,
      168,  170,  175,  173,  180,  182,  184,  146,  290,  288,
      195,  187,  197,  329,  329,  329,  329,    0,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  202,
        0,  207,  200,  329,  209,    0,  329,  282,  329,  279,
      329,  276,  329,  237,  329,  224,  329,  236,  226,  214,
      329,  231,    0,    0,  233,    0,  238,    0,  329,  329,
      329,  329,  244,  247,  250,  253,  256,  259,  262,  265,

      268,  271,  274,  277,  280,  283,  235,  286,  228,  289,
      211,  133,  118,  101,   94,   74,   50,   42,   40,   21
    } ;

static yyconst short int yy_def[221] =
    {   0,
      193,  193,  194,  194,  195,  195,  196,  196,  197,  197,
      198,  198,  199,  199,  200,  200,  201,  201,  202,  202,
      203,  203,  204,  204,  192,  192,  192,  192,  192,  192,
      192,  205,  205,  205,  205,  205,  205,  205,  205,  192,
      192,  192,  192,  192,  192,  206,  207,  192,  192,  192,
      192,  192,  192,  192,  208,  209,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      210,  211,  192,  192,  192,  192,  192,  192,  192,  205,
      205,  205,  205,  205,  205,  205,  192,  192,  205,  205,

      192,  192,  205,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  212,  192,  192,  192,  192,  192,  192,  192,
      213,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  214,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      215,  192,  192,  192,  192,  216,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  217,  218,  192,  219,  192,  220,  192,  192,
      192,    0,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192
    } ;

static yyconst short int yy_nxt[358] =
    {   0,
      192,   27,   28,   27,   28,   30,   31,   30,   31,   29,
       59,   60,   59,   60,   69,   70,   69,   70,   85,   86,
       87,   88,   61,  191,   61,   33,   34,   35,   98,   36,
       37,   38,   39,   29,   72,   73,   72,   73,   89,   89,
      106,  107,  190,   99,  189,  102,   74,  100,   74,   33,
       34,   35,  188,   36,   37,   38,   39,   41,   42,   43,
       44,  103,  108,  108,  114,  115,  116,  116,  122,  123,
       45,   46,  127,  128,  129,  130,  186,  124,  131,  132,
      133,  134,   47,   48,   41,   42,   43,   44,  125,  135,
      135,  136,  137,  138,  141,  142,  184,   45,   46,  143,

      143,   85,   86,  183,  139,   87,   88,   89,   89,   47,
       48,   50,   51,   52,   53,   89,   89,  106,  107,  149,
      166,  159,  160,  107,   54,   55,  108,  108,  162,  163,
      165,  115,  164,  116,  116,  161,   56,   57,   50,   51,
       52,   53,  122,  123,  168,  123,  167,  124,  138,  127,
      128,   54,   55,  169,  170,  128,  129,  130,  125,  139,
      171,  172,  130,   56,   57,   76,   77,   78,   79,  131,
      132,  174,  132,  173,  176,  134,  133,  134,   80,   81,
      175,  135,  135,  136,  137,  178,  137,  177,  182,  142,
       82,   83,   76,   77,   78,   79,  179,  180,  143,  143,

      181,  185,  163,  108,  108,   80,   81,  159,  162,  163,
      116,  116,  164,  148,  164,  187,  180,   82,   83,   91,
       92,   93,   94,   95,   96,  135,  135,  179,  180,  175,
      121,  181,  143,  143,  116,  116,  181,  113,  164,  143,
      143,  177,  173,  181,   26,   26,   26,   29,   29,   29,
       32,   32,   32,   40,   40,   40,   49,   49,   49,   58,
       58,   58,   62,   62,   62,   64,   64,   64,   66,   66,
       66,   68,   68,   68,   71,   71,   71,   75,   75,   75,
       90,  171,   90,  112,  169,  112,  120,  167,  120,  147,
      140,  147,  140,  126,  126,  158,  157,  156,  155,  154,

      153,  152,  151,  150,   84,  146,  145,  144,  140,  126,
      119,  118,  117,  111,  110,  109,  105,  104,  101,   97,
       84,  192,   67,   67,   65,   65,   63,   63,   25,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192
    } ;

static yyconst short int yy_chk[358] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    4,    4,    5,
       11,   11,   12,   12,   19,   19,   20,   20,   28,   28,
       30,   30,   11,  220,   12,    5,    5,    5,   35,    5,
        5,    5,    5,    6,   21,   21,   22,   22,   31,   31,
       41,   41,  219,   35,  218,   37,   21,   35,   22,    6,
        6,    6,  217,    6,    6,    6,    6,    7,    7,    7,
        7,   37,   42,   42,   50,   50,   51,   51,   59,   59,
        7,    7,   63,   63,   65,   65,  216,   60,   67,   67,
       69,   69,    7,    7,    8,    8,    8,    8,   60,   70,
       70,   72,   72,   73,   76,   76,  215,    8,    8,   77,

       77,   86,   86,  214,   73,   88,   88,   89,   89,    8,
        8,    9,    9,    9,    9,   87,   87,  106,  106,   87,
      213,  106,  107,  107,    9,    9,  108,  108,  114,  114,
      115,  115,  114,  116,  116,  212,    9,    9,   10,   10,
       10,   10,  122,  122,  123,  123,  122,  124,  138,  127,
      127,   10,   10,  127,  128,  128,  129,  129,  124,  138,
      129,  130,  130,   10,   10,   23,   23,   23,   23,  131,
      131,  132,  132,  131,  134,  134,  133,  133,   23,   23,
      133,  135,  135,  136,  136,  137,  137,  136,  142,  142,
       23,   23,   24,   24,   24,   24,  141,  141,  143,  143,

      141,  163,  163,  160,  160,   24,   24,  160,  162,  162,
      165,  165,  162,  211,  165,  180,  180,   24,   24,   33,
       33,   33,   33,   33,   33,  176,  176,  179,  179,  176,
      209,  179,  182,  182,  185,  185,  182,  207,  185,  187,
      187,  178,  174,  187,  193,  193,  193,  194,  194,  194,
      195,  195,  195,  196,  196,  196,  197,  197,  197,  198,
      198,  198,  199,  199,  199,  200,  200,  200,  201,  201,
      201,  202,  202,  202,  203,  203,  203,  204,  204,  204,
      205,  172,  205,  206,  170,  206,  208,  168,  208,  210,
      140,  210,  139,  126,  125,  103,  100,   99,   96,   95,

       94,   93,   92,   91,   85,   80,   79,   78,   74,   61,
       54,   53,   52,   45,   44,   43,   39,   38,   36,   34,
       27,   25,   18,   17,   16,   15,   14,   13,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "em2htm5.l"
#define INITIAL 0
#line 2 "em2htm5.l"


#define PARA1 0
#define HEAD1 1
#define HEAD2 2
#define HEAD3 3
#define HEAD4 4
#define HEAD5 5
#define HEAD6 6

#define NONE 0
#define EMPHASIS 1
#define STRONG 2
#define CODE 3

#define ULIST 0
#define NUMLIST 1

#define TABLE1 0

#define VERBATIM1 0

#define IMG1 0

#define DEFLIST1 0


#define TITLE 1
#define COMMAND 2
#define PARA 3
#define LIST 4
#define TABLE 5
#define VERBATIM 6
#define XTRA 7
#define IMG_A 8
#define IMG_B 9
#define DEFLIST_A 10
#define DEFLIST_B 11

int html_ver; 
int para_block;
int inline;
int inline_type;
int list_block;
int table_block;
int table_header;
int verbatim_block;
int img_block;
int deflist_block;
void title_open(void);
void title_close(void);
void para_block_open(void);
void para_block_close(void);
void inline_open(void);
void inline_close(void);
void put_char(char);
void list_block_open(void);
void list_block_close(void);
void list_item_open(void);
void list_item_close(void);
void table_block_open(void);
void table_block_close(void);
void table_row_open(void);
void table_row_close(void);
void table_col_open(void);
void table_col_open_th(void);
void table_col_close(void);
void table_col_close_th(void);
void verbatim_block_open(void);
void verbatim_block_close(void);
void img_block_open(void);
void img_block_alt(void);
void img_block_close(void);
void deflist_block_open(void);
void deflist_block_close(void);
void deflist_term_open(void);
void deflist_term_close(void);
void deflist_def_open(void);
void deflist_def_close(void);
#line 588 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 93 "em2htm5.l"


#line 742 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 193 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 329 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 95 "em2htm5.l"
deflist_term_close(); deflist_def_open(); deflist_def_close(); deflist_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(DEFLIST_A):
#line 96 "em2htm5.l"
deflist_term_close(); deflist_def_open(); deflist_def_close(); deflist_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "em2htm5.l"
deflist_term_close(); deflist_def_open(); BEGIN(DEFLIST_B); 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "em2htm5.l"
deflist_term_close(); deflist_def_open(); BEGIN(DEFLIST_B); 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "em2htm5.l"
put_char(yytext[1]);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "em2htm5.l"
printf("&#x%c%c%c%c;", yytext[1], yytext[2], yytext[3], yytext[4]);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "em2htm5.l"
inline = EMPHASIS; inline_type = 1; inline_open();
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "em2htm5.l"
inline = STRONG; inline_type = 1; inline_open();
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "em2htm5.l"
inline = CODE; inline_type = 1; inline_open();
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "em2htm5.l"
inline_close(); inline = NONE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "em2htm5.l"
inline = EMPHASIS; inline_type = 0; inline_open();
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "em2htm5.l"
inline = STRONG; inline_type = 0; inline_open();
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "em2htm5.l"
inline = CODE; inline_type = 0; inline_open();
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "em2htm5.l"
inline_close(); deflist_def_close(); deflist_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(DEFLIST_B):
#line 115 "em2htm5.l"
inline_close(); deflist_def_close(); deflist_block_close(); BEGIN(COMMAND);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "em2htm5.l"
inline_close(); deflist_def_close(); deflist_term_open(); BEGIN(DEFLIST_A); 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 117 "em2htm5.l"
if (inline_type == 0){ inline_close(); inline = NONE; } put_char(' ');
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 118 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "em2htm5.l"
img_block_alt(); img_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(IMG_A):
#line 122 "em2htm5.l"
img_block_alt(); img_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 123 "em2htm5.l"
img_block_alt(); BEGIN(IMG_B); 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "em2htm5.l"
printf("%c", yytext[0]);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "em2htm5.l"
img_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(IMG_B):
#line 127 "em2htm5.l"
img_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 128 "em2htm5.l"
put_char(' ');
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 129 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 132 "em2htm5.l"
BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(XTRA):
#line 133 "em2htm5.l"
BEGIN(COMMAND);  
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 134 "em2htm5.l"
printf("\n", yytext[0]);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "em2htm5.l"
printf("%c", yytext[0]);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 138 "em2htm5.l"
verbatim_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(VERBATIM):
#line 139 "em2htm5.l"
verbatim_block_close(); BEGIN(COMMAND);  
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 140 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 141 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 144 "em2htm5.l"
if (table_header == 1){ table_col_close_th(); } else { table_col_close(); } table_row_close(); table_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(TABLE):
#line 145 "em2htm5.l"
if (table_header == 1){ table_col_close_th(); } else { table_col_close(); } table_row_close(); table_block_close(); BEGIN(COMMAND);  
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 147 "em2htm5.l"
if (table_header == 1){ table_col_close_th(); } else { table_col_close(); } table_row_close(); table_header = 0; table_row_open(); table_col_open();
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 148 "em2htm5.l"
if (table_header == 1){ table_col_close_th(); } else { table_col_close(); } if (table_header == 1){ table_col_open_th(); } else { table_col_open(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 149 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 150 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "em2htm5.l"
put_char(yytext[1]);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 155 "em2htm5.l"
printf("&#x%c%c%c%c;", yytext[1], yytext[2], yytext[3], yytext[4]);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 157 "em2htm5.l"
inline = EMPHASIS; inline_type = 1; inline_open();
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 158 "em2htm5.l"
inline = STRONG; inline_type = 1; inline_open();
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 159 "em2htm5.l"
inline = CODE; inline_type = 1; inline_open();
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 160 "em2htm5.l"
inline_close(); inline = NONE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 162 "em2htm5.l"
inline = EMPHASIS; inline_type = 0; inline_open();
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 163 "em2htm5.l"
inline = STRONG; inline_type = 0; inline_open();
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 164 "em2htm5.l"
inline = CODE; inline_type = 0; inline_open();
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 166 "em2htm5.l"
inline_close(); list_item_close(); list_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(LIST):
#line 167 "em2htm5.l"
inline_close(); list_item_close(); list_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 168 "em2htm5.l"
inline_close(); list_item_close(); list_item_open(); 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 169 "em2htm5.l"
if (inline_type == 0){ inline_close(); inline = NONE; } put_char(' ');
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 170 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 173 "em2htm5.l"
put_char(yytext[1]);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 175 "em2htm5.l"
printf("&#x%c%c%c%c;", yytext[1], yytext[2], yytext[3], yytext[4]);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 177 "em2htm5.l"
inline = EMPHASIS; inline_type = 1; inline_open();
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "em2htm5.l"
inline = STRONG; inline_type = 1; inline_open();
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 179 "em2htm5.l"
inline = CODE; inline_type = 1; inline_open();
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 180 "em2htm5.l"
inline_close(); inline = NONE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 182 "em2htm5.l"
inline = EMPHASIS; inline_type = 0; inline_open();
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 183 "em2htm5.l"
inline = STRONG; inline_type = 0; inline_open();
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 184 "em2htm5.l"
inline = CODE; inline_type = 0; inline_open();
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 186 "em2htm5.l"
inline_close(); para_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case YY_STATE_EOF(PARA):
#line 187 "em2htm5.l"
inline_close(); para_block_close(); BEGIN(COMMAND); 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 188 "em2htm5.l"
if (inline_type == 0){ inline_close(); inline = NONE; } put_char(' ');
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 189 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 192 "em2htm5.l"
deflist_block = DEFLIST1; inline = NONE; inline_type = 0; deflist_block_open(); deflist_term_open(); BEGIN(DEFLIST_A);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 193 "em2htm5.l"
img_block = IMG1; img_block_open(); BEGIN(IMG_A);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 194 "em2htm5.l"
BEGIN(XTRA);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 195 "em2htm5.l"
verbatim_block = VERBATIM1; verbatim_block_open(); BEGIN(VERBATIM);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 196 "em2htm5.l"
table_block = TABLE1; table_header = 1; table_block_open(); table_row_open(); table_col_open_th(); BEGIN(TABLE);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 197 "em2htm5.l"
table_block = TABLE1; table_header = 0; table_block_open(); table_row_open(); table_col_open(); BEGIN(TABLE);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 198 "em2htm5.l"
list_block = NUMLIST; inline = NONE; inline_type = 0; list_block_open(); list_item_open(); BEGIN(LIST);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 199 "em2htm5.l"
list_block = ULIST; inline = NONE; inline_type = 0; list_block_open(); list_item_open(); BEGIN(LIST);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 200 "em2htm5.l"
para_block = HEAD6; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 201 "em2htm5.l"
para_block = HEAD5; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 202 "em2htm5.l"
para_block = HEAD4; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 203 "em2htm5.l"
para_block = HEAD3; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 204 "em2htm5.l"
para_block = HEAD2; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 205 "em2htm5.l"
para_block = HEAD1; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "em2htm5.l"
para_block = PARA1; inline = NONE; inline_type = 0; para_block_open(); BEGIN(PARA);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "em2htm5.l"
BEGIN(0);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 209 "em2htm5.l"
title_close(); BEGIN(COMMAND);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 210 "em2htm5.l"
put_char(' ');
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 211 "em2htm5.l"
put_char(yytext[0]);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 213 "em2htm5.l"
title_close(); BEGIN(COMMAND);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 214 "em2htm5.l"
put_char(yytext[0]); BEGIN(TITLE);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 215 "em2htm5.l"

	YY_BREAK
case 82:
YY_RULE_SETUP
#line 218 "em2htm5.l"
ECHO;
	YY_BREAK
#line 1271 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TITLE):
case YY_STATE_EOF(COMMAND):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 193 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 193 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 192);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 218 "em2htm5.l"


  

void title_open()
{
 
    printf("<title>");

}



void title_close()
{

    printf("</title></head><body>");

}


void para_block_open()
{


    switch (para_block){
        case PARA1 :
            printf("<p>");
            break;
        case HEAD1 :
            printf("<h1>");
            break;
        case HEAD2 :
            printf("<h2>");
            break;
        case HEAD3 :
            printf("<h3>");
            break;
        case HEAD4 :
            printf("<h4>");
            break;
        case HEAD5 :
            printf("<h5>");
            break;
        case HEAD6 :
            printf("<h6>");
            break;

    }

}


void para_block_close()
{


    switch (para_block){
        case PARA1 :
            printf("</p>");
            break;
        case HEAD1 :
            printf("</h1>");
            break;
        case HEAD2 :
            printf("</h2>");
            break;
        case HEAD3 :
            printf("</h3>");
            break;
        case HEAD4 :
            printf("</h4>");
            break;
        case HEAD5 :
            printf("</h5>");
            break;
        case HEAD6 :
            printf("</h6>");
            break;

    }

}


void inline_open()
{


    switch (inline){
        case EMPHASIS :
            printf("<em>");
            break;
        case STRONG :
            printf("<strong>");
            break;
        case CODE :
            printf("<code>");
            break;

    }

}


void inline_close()
{


    switch (inline){
        case EMPHASIS :
            printf("</em>");
            break;
        case STRONG :
            printf("</strong>");
            break;
        case CODE :
            printf("</code>");
            break;

    }

}


void put_char(char ch)
{


    switch (ch){
        case '"' :
            printf("&quot;");
            break;
        case '&' :
            printf("&amp;");
            break;
        case 0x27 :
            printf("&apos;");
            break;
        case '<' :
            printf("&lt;");
            break;
        case '>' :
            printf("&gt;");
            break;
        default :
            printf("%c", ch);
            break;

    }

}


void list_block_open()
{


    switch (list_block){
        case ULIST :
            printf("<ul>");
            break;
        case NUMLIST :
            printf("<ol>");
            break;
    }

}


void list_block_close()
{


    switch (list_block){
        case ULIST :
            printf("</ul>");
            break;
        case NUMLIST :
            printf("</ol>");
            break;
    }

}


void list_item_open()
{


    switch (list_block){
        case ULIST :
            printf("<li>");
            break;
        case NUMLIST :
            printf("<li>");
            break;
    }

}


void list_item_close()
{


    switch (list_block){
        case ULIST :
            printf("</li>");
            break;
        case NUMLIST :
            printf("</li>");
            break;
    }

}


void table_block_open()
{


    switch (table_block){
        case TABLE1 :
            printf("<table>");
            break;
    }

}


void table_block_close()
{


    switch (table_block){
        case TABLE1 :
            printf("</table>");
            break;
    }

}


void table_row_open()
{


    switch (table_block){
        case TABLE1 :
            printf("<tr>");
            break;
    }

}


void table_row_close()
{


    switch (table_block){
        case TABLE1 :
            printf("</tr>");
            break;
    }

}



void table_col_open()
{


    switch (table_block){
        case TABLE1 :
            printf("<td>");
            break;
    }

}


void table_col_close()
{


    switch (table_block){
        case TABLE1 :
            printf("</td>");
            break;
    }

}



void table_col_open_th()
{


    switch (table_block){
        case TABLE1 :
            printf("<th>");
            break;
    }

}


void table_col_close_th()
{


    switch (table_block){
        case TABLE1 :
            printf("</th>");
            break;
    }

}


void verbatim_block_open()
{


    switch (verbatim_block){
        case VERBATIM1 :
            printf("<pre>");
            break;
    }

}


void verbatim_block_close()
{


    switch (verbatim_block){
        case VERBATIM1 :
            printf("</pre>");
            break;
    }

}


void img_block_open()
{


    switch (img_block){
        case IMG1 :
            printf("<img src=\"");
            break;
    }

}


void img_block_alt()
{


    switch (img_block){
        case IMG1 :
            printf("\" alt=\"");
            break;
    }

}


void img_block_close()
{


    switch (img_block){
        case IMG1 :
            printf("\">");
            break;
    }

}


void deflist_block_open()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("<dl>");
            break;
    }

}


void deflist_block_close()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("</dl>");
            break;
    }

}


void deflist_term_open()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("<dt>");
            break;
    }

}


void deflist_term_close()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("</dt>");
            break;
    }

}


void deflist_def_open()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("<dd>");
            break;
    }

}


void deflist_def_close()
{


    switch (deflist_block){
        case DEFLIST1 :
            printf("</dd>");
            break;
    }

}


int yywrap()
{
    return 1;
}


int main(int argc, char *argv[])
{

    html_ver = 5;   /* 4 = html4  5 = html5 */

    para_block = PARA1;
    inline = NONE;
    inline_type = 0;

    if ((argc > 3)){

        fprintf(stderr, "Usage: em2htm < infile.txt > outfile.htm\n\n");
        fprintf(stderr, "em2htm file.css < infile.txt > outfile.htm\n\n");
        fprintf(stderr, "em2htm file.css print.css < infile.txt > outfile.htm\n\n");

        exit(1);
    }


    if (html_ver == 4){

        printf("<!DOCTYPE HTML PUBLIC \x22-//W3C//DTD HTML 4.01 Transitional//EN\x22 ");
        printf("\x22http://www.w3.org/TR/html4/loose.dtd\x22>");
        printf("<html><head><meta http-equiv=\x22");
        printf("Content-Type\x22 content=\x22text/html;charset=ISO-8859-1\x22>");

    }

    else if (html_ver == 5){

        printf("<!DOCTYPE html>");
        printf("<html><head><meta http-equiv=\x22");
        printf("Content-Type\x22 content=\x22text/html;charset=ISO-8859-1\x22>");

    }


    if (argc > 1){

        printf("<link rel=\x22stylesheet\x22 type=\x22text/css\x22 href=\x22%s\x22>", argv[1]); 

    }

    if (argc > 2){

        printf("<link rel=\x22stylesheet\x22 type=\x22text/css\x22 href=\x22%s\x22 media=\x22print\x22>", argv[2]); 

    }


    title_open();

    yylex();

  
    printf("</body></html>");

    return 0;

}
